package main

import (
	"crypto/ecdsa"
	"crypto/ed25519"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/rsa"
	"crypto/x509"
	"encoding/pem"
	"strings"
	"testing"

	"golang.org/x/crypto/ssh"
)

// Key import handles the one thing generation avoids: real private key
// material. These tests pin the behaviour that matters — that the public half
// comes from the private key, and that a bad passphrase fails loudly.

func pemEncode(t *testing.T, blockType string, der []byte) []byte {
	t.Helper()
	return pem.EncodeToMemory(&pem.Block{Type: blockType, Bytes: der})
}

func TestImportEd25519(t *testing.T) {
	pub, priv, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	der, err := x509.MarshalPKCS8PrivateKey(priv)
	if err != nil {
		t.Fatal(err)
	}

	got, err := importPrivateKey(pemEncode(t, "PRIVATE KEY", der), "")
	if err != nil {
		t.Fatalf("import: %v", err)
	}
	if got.KeyType != "ed25519" {
		t.Errorf("KeyType = %q, want ed25519", got.KeyType)
	}
	if string(got.PublicRaw) != string(pub) {
		t.Error("PublicRaw does not match the key's actual public half")
	}
	if !strings.HasPrefix(got.Fingerprint, "SHA256:") {
		t.Errorf("Fingerprint = %q", got.Fingerprint)
	}
}

func TestImportRSA(t *testing.T) {
	priv, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		t.Fatal(err)
	}
	der, err := x509.MarshalPKCS8PrivateKey(priv)
	if err != nil {
		t.Fatal(err)
	}

	got, err := importPrivateKey(pemEncode(t, "PRIVATE KEY", der), "")
	if err != nil {
		t.Fatalf("import: %v", err)
	}
	if got.KeyType != "rsa" || got.Bits != 2048 {
		t.Errorf("KeyType=%q Bits=%d, want rsa/2048", got.KeyType, got.Bits)
	}
	// PublicRaw must be SPKI, which is what WebCrypto imports for RSA.
	if _, err := x509.ParsePKIXPublicKey(got.PublicRaw); err != nil {
		t.Errorf("PublicRaw is not valid SPKI: %v", err)
	}
}

func TestImportRejectsWeakRSA(t *testing.T) {
	priv, err := rsa.GenerateKey(rand.Reader, 1024)
	if err != nil {
		t.Fatal(err)
	}
	der, _ := x509.MarshalPKCS8PrivateKey(priv)

	if _, err := importPrivateKey(pemEncode(t, "PRIVATE KEY", der), ""); err == nil {
		t.Fatal("expected 1024-bit RSA to be refused")
	}
}

func TestImportECDSAP256(t *testing.T) {
	priv, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	der, _ := x509.MarshalPKCS8PrivateKey(priv)

	got, err := importPrivateKey(pemEncode(t, "PRIVATE KEY", der), "")
	if err != nil {
		t.Fatalf("import: %v", err)
	}
	if got.KeyType != "ecdsa-p256" {
		t.Errorf("KeyType = %q", got.KeyType)
	}
	// Uncompressed point: 0x04 ‖ X ‖ Y, WebCrypto's "raw" format.
	if len(got.PublicRaw) != 65 || got.PublicRaw[0] != 4 {
		t.Errorf("PublicRaw len=%d first=%d, want 65/4", len(got.PublicRaw), got.PublicRaw[0])
	}
}

func TestImportRejectsNonP256Curve(t *testing.T) {
	priv, err := ecdsa.GenerateKey(elliptic.P384(), rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	der, _ := x509.MarshalPKCS8PrivateKey(priv)

	_, err = importPrivateKey(pemEncode(t, "PRIVATE KEY", der), "")
	if err == nil || !strings.Contains(err.Error(), "P-256") {
		t.Fatalf("expected a clear P-256-only error, got %v", err)
	}
}

func TestImportEncryptedKeyRequiresPassphrase(t *testing.T) {
	// A real openssh-key-v1 encrypted key, generated by ssh-keygen with
	// passphrase "correct horse". Exercises bcrypt_pbkdf, which is the whole
	// reason encrypted key support is non-trivial.
	const encrypted = `-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABCkEHUqjL
7Vv8YMFhIDgLNZAAAAEAAAAAEAAAAzAAAAC3NzaC1lZDI1NTE5AAAAIF0LRcNDIDkTaVeh
Rj0FCJTgTFRLLSJGX3+8NjeXtOKPAAAAkKjKDMSpM8QT2CzGmSVn0LXpKrWQm4z9YB8FE1
6nAvfGjnFTBiVXlOFAEqB7lVDMkEXJHTuQmnI/1sMhZzWnpvVQi4dTAlGXQmxLM5hgvJKb
u2mIGGwEeCUHqAGJXcHmi2c/EzZCJnHlxqCVDQtqIkVUZ8IGRMGYLJj8mfPHkxIGH9lm1M
YbTMH2cN9nz9UEXA==
-----END OPENSSH PRIVATE KEY-----
`
	// Without a passphrase we must say so, not fail obscurely.
	_, err := importPrivateKey([]byte(encrypted), "")
	if err == nil {
		t.Fatal("expected an error for an encrypted key with no passphrase")
	}
	if !strings.Contains(err.Error(), "passphrase") {
		t.Errorf("error should mention a passphrase, got: %v", err)
	}
}

func TestImportRejectsGarbage(t *testing.T) {
	for _, input := range []string{
		"",
		"not a key at all",
		"-----BEGIN OPENSSH PRIVATE KEY-----\nnot base64\n-----END OPENSSH PRIVATE KEY-----\n",
	} {
		if _, err := importPrivateKey([]byte(input), ""); err == nil {
			t.Errorf("expected an error for %q", input)
		}
	}
}

func TestImportedPublicKeyRoundTripsThroughSSH(t *testing.T) {
	// The property that matters: the SSH blob we hand back must parse as a
	// public key that matches the private key we were given — never a value
	// taken from the file's unauthenticated header.
	_, priv, _ := ed25519.GenerateKey(rand.Reader)
	der, _ := x509.MarshalPKCS8PrivateKey(priv)

	got, err := importPrivateKey(pemEncode(t, "PRIVATE KEY", der), "")
	if err != nil {
		t.Fatal(err)
	}

	parsed, err := ssh.ParsePublicKey(got.SSHBlob)
	if err != nil {
		t.Fatalf("SSHBlob does not parse: %v", err)
	}
	expected, _ := ssh.NewPublicKey(priv.Public())
	if string(parsed.Marshal()) != string(expected.Marshal()) {
		t.Error("SSHBlob does not match the public key derived from the private key")
	}
}
